version: '3.8'

services:
  catalogdb:
    image: postgres:18
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerr112358
      POSTGRES_DB: CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql
 
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DbConnectionString=Server=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=qwerr112358
    depends_on:
          - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
